### ISSUE TITLE
different Gnet used in paper and codes

### ISSUE THREAD

**Issue by YuGuilliman** [Wang-ML-Lab/TSDA#2]

**Comment by YuGuilliman** [comment]
in your paper, you said "you first leverage an intermediate domain embedding zul = g(ul, A) to capture the immediate dependency between ul and A“, but in codes,  " self.z_seq = self.netG(self.one_hot_seq) " which means that you did not use the   distance matrix A .

**Comment by shsjxzh** [comment]
Hi YuGilliman,

"G" is a graph embedding generator pre-trained with the distance matrix, and "one_hot_seq" is a one-hot vector indicating the domain where the sample originates. It's correct that we don't directly use the distance matrix. Instead, we implicitly encode such information in the pre-trained "G." For more details, please refer to Appendix B.1, Model Architecture.

Best,
Zihao

**Comment by YuGuilliman** [comment]
Thank you for your quick reply. Can you please deliver the pre-train code? I am a fresh man in this area and still confused about the shape transformation in it. While pre-train, Gnet( or the taxonomy encoder) takes distance matrix A (shape nd * nd) and domian indice ul (shape 1 * nd) as input. But in the formal formal training process, Gnet takes only ul as input. I don't understand how  the nets take the inputs in different shape can be the one?

**Comment by shsjxzh** [comment]
Hi Yugilliman,

For the pretraining of G, please refer to function "__loss_GR__()" and "__optimize_TSDA__". In the paper, we write in that way to ease the burden of understanding. However, in the implementation, we do not explicitly take A as the input to the Gnet.

Best,
Zihao

**Comment by YuGuilliman** [comment]
Thank you for your help!
