### ISSUE TITLE
Hello, I changed the number of categories from 2 to 5 in the configuration file, and the effect of the classification task is very poor, only 20%, may I ask why?

### ISSUE THREAD

**Issue by QZRUSSELL** [Wang-ML-Lab/TSDA#3]
Hello, I changed the number of categories from 2 to 5 in the configuration file, and the effect of the classification task is very poor, only 20%, may I ask why?

**Comment by QZRUSSELL** [comment]
![H450 TZ@YAQ013@{89D70V3](https://github.com/Wang-ML-Lab/TSDA/assets/132912410/38509f3f-8cb6-4b05-99c5-9becea2a6e41)
I used my own dataset, which was a five-classification task for two domains.

**Comment by shsjxzh** [comment]
Hi QZRUSSELL,

There are 2 possible reasons:
1. For 2 category cases, our method will degrade to the traditional DANN method. Our method is more suitable for multi-source, multi-target setting.
2. The discriminator loss is 0 ('D': 0.0), indicating that the adversarial learning is not working. You may need to review the hyper parameters for this issue.

Best,
Zihao
